name: Build 

on:
  push:
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Install Deps
        run: |
          # Add Docker's official GPG key:
          sudo apt-get -y update
          sudo apt-get install -y ca-certificates curl
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc

          # Add the repository to Apt sources:
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
            $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update -y 
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
          
          # INSTALL SCOUT COMMAND
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
          sh install-scout.sh
          
      - name: Build Docker
        run: |
          docker build -t joffreydupire/voting-app:latest .

      - name: Docker Login
        run: |
          docker login -u joffreydupire -p ${{ secrets.DOCKER_TOKEN }}

      - name: Docker scout
        run: |
          docker scout cves joffreydupire/voting-app:latest

      - name: Docker push
        run: |
          docker push joffreydupire/voting-app:latest